services:
  - type: web
    name: ecommerce-backend
    runtime: node
    buildCommand: npm install --prefix backend
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
